#define INT_SECONDS_KEY 1
#define INT_NANO_SECONDS_KEY 2
#define NUM_SECONDS_WAIT 100
#define FILENAME_LENGTH 100
#define DEBUG_OUTPUT
#define INT_CRITICAL_MESSAGE 3
#define INT_COMMUNICATION_MESSAGE 4
#define NANO_PER_SECOND 1000000000
#define MAX_NUM_PROCESSES 100 
#define TOTAL_SECONDS_TIME 2 
